dist: trusty
sudo: false
git:
  # use depth 2 just in case two refs get pushed at once (like a tag)
  depth: 2
language: ruby
cache: bundler
bundler_args: --path=.bundle/gems
rvm:
- &release_ruby 2.5.3
- 2.4.5
- 2.3.8
- 1.9.3
script: bundle exec asciidoctor-pdf -o test.pdf examples/chronicles-example.adoc
deploy:
  provider: rubygems
  on:
    tags: true
    repo: asciidoctor/asciidoctor-pdf
    rvm: *release_ruby
  api_key:
    secure: bzAbFi7YT7bb/5gAePjw11Ghzbh+tOqMlL1Xn+o5pyseSNRDB5tDcocL0fbAcHkSBzaC/36m2apvdt0xmNYCmRLJyZtCS6lQtzW5j9hUXfCDnf8HmX0o785TtlUwk6qNqwd9v0GZGK58hts44K3mHtK/we9+5ucp3EhmP8l4MWE=
